root_dir: 'C:\Users\ASUS\OneNeuron\practice\dt2_sk2co'

prediction:
  temp_data: './temp_data'
  out_dir: "HTML output"

training:


detection_config:
  config_file: "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
  num_classes: 14
  score_thresh_test: 0.5
  model_name: 'model_final.pth'
  model_folder: 'output2'
