_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  DEVICE: "cpu"
  ROI_HEADS:
    NUM_CLASSES: 2
    SCORE_THRESH_TEST: 0.7
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
SOLVER:
  BASE_LR: 0.00025
  IMS_PER_BATCH: 2
  MAX_ITER: 270000
DATALOADER:
  NUM_WORKERS: 2